

# # # # # numero = 6
# # # # # numero1 = 4
# # # # # mult = (numero*numero1)
# # # # # resultado = int(mult/2)
# # # # # print(resultado)

# # # # # numero = 5 
# # # # # numero1 = 7
# # # # # soma = (numero + numero1)
# # # # # print(soma)



# # # # # numero1 = 3
# # # # # numero2 = 4
# # # # # ele = (numero1**numero2)
# # # # # print(ele)

# # # # numero = 5 
# # # # cubo = (numero**3)
# # # # print(cubo)

# # # lista = [8,12,15]
# # # soma = sum(lista)
# # # media = int(soma/3)
# # # print(media)

# # numero = 10 
# # numero1 = 1 
# # mult = (numero-numero1)
# # resultado = int(mult*5)
# # print(resultado)


# numero1 = 27
# numero2 = 3
# div = (numero1 // numero2)
# resultado = (div+3)
# print(resultado)

# raiz_quadrada = 81**(1/2)
# print(raiz_quadrada)


